### ISSUE TITLE
E720: Missing colon in Dictionary

### ISSUE THREAD

**Issue by arozehnal** [girishji/vimsuggest#1]
I just tried to incorporate a sample configuration
Completing the command configuration
Search completion configuration

and I got
E720: Missing colon in dictionary: 'fuzzy': v:false, " Enable fuzzy completion matching 'exclude': [], ' Regex patterns to exclude from completion 'onspace': [], " Commands to complete after space (e. g, 'buffer') 'alwayson': v:true, " Automatically open menu (v:false to open with <Tab>) 'popupattrs': { ' Passed directly to `popup_menu()` 'maxHeight': 12 ' Maximum number of lines in stacked menu (pum = v: true) }, 'wildignore': v:true, ' Respect 'wildignore' when completing the file 'addons': v:true, ' Enable addons (`:VSxxx` commands) 'ctrl_np': false, ' <C-n/p> selects menu if 'true'; otherwise retrieves history }
Press ENTER or enter a command to continue

Then I noticed a slight discrepancy between the README.MD and the plugin help.
But both variants end with the same error.

OS: Win10 Pro
VIM 9.1 (Included patches: 1-698) + vim-plug manager

**Comment by girishji** [comment]
Pl. try now. Remove all comments.

**Comment by arozehnal** [comment]
I only did a reinstallation of the plugin (without intervention in the configuration).
After running "gvim" I get:
![image](https://github.com/user-attachments/assets/b074f9fe-6384-46bd-934b-edc7e7183e14)

but PlugStatus is reporting  
   vimsuggest: OK

I tried to install vimsuggest into vim on AIX. There is no poblem when running vim.

**Comment by girishji** [comment]
Says "Could not import ...". Can you do `:version` and post the output?

**Comment by arozehnal** [comment]
`VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan  2 2024 23:51:27)
MS-Windows 64-bit GUI version with OLE support
Compiled by appveyor@APPVEYOR-VM
Huge version with GUI.  Features included (+) or not (-):
+acl                +ex_extra           +mzscheme/dyn       -tcl
+arabic             +extra_search       +netbeans_intg      -termguicolors
+autocmd            -farsi              +num64              +terminal
+autochdir          +file_in_path       +ole                -termresponse
+autoservername     +find_in_path       +packages           +textobjects
+balloon_eval       +float              +path_extra         +textprop
-balloon_eval_term  +folding            +perl/dyn           -tgetent
+browse             -footer             +persistent_undo    +timers
++builtin_terms     +gettext/dyn        +popupwin           +title
+byte_offset        -hangul_input       -postscript         +toolbar
+channel            +iconv/dyn          +printer            +user_commands
+cindent            +insert_expand      +profile            +vartabs
+clientserver       +ipv6               +python/dyn         +vertsplit
+clipboard          +job                +python3/dyn-stable +vim9script
+cmdline_compl      +jumplist           +quickfix           +viminfo
+cmdline_hist       +keymap             +reltime            +virtualedit
+cmdline_info       +lambda             +rightleft          +visual
+comments           +langmap            +ruby/dyn           +visualextra
+conceal            +libcall            +scrollbind         +vreplace
+cryptv             +linebreak          +signs              -vtp
+cscope             +lispindent         +smartindent        +wildignore
+cursorbind         +listcmds           +sodium/dyn         +wildmenu
+cursorshape        +localmap           +sound              +windows
+dialog_con_gui     +lua/dyn            +spell              +writebackup
+diff               +menu               +startuptime        -xattr
+digraphs           +mksession          +statusline         -xfontset
+directx            +modify_fname       -sun_workshop       -xim
-dnd                +mouse              +syntax             +xpm_w32
-ebcdic             +mouseshape         +tag_binary         -xterm_save
+emacs_tags         +multi_byte_ime/dyn -tag_old_static     
+eval               +multi_lang         -tag_any_white      
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32 -DHAVE_STDINT_H  -DFEAT_CSCOPE 
-DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6 
-DHAVE_INET_NTOP   -DFEAT_XPM_W32 -DHAVE_SODIUM -DDYNAMIC_SODIUM -DDYNAMIC_SODIUM_DLL=\"li
bsodium.dll\" /I "C:\projects\vim-win32-installer\dependencies\libsodium\include" -DWINVER=0x0601 
-D_WIN32_WINNT=0x0601 /source-charset:utf-8 /MP /Ox /GL -DNDEBUG /Zl /MT /D_CRT_SECURE_NO_DEPRECA
TE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN 
-DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV 
-DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON 
-DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 
-DDYNAMIC_PYTHON3_DLL=\"python3.dll\" -DDYNAMIC_PYTHON3_STABLE_ABI -DFEAT_MZSCHEME -I 
"C:\projects\vim-win32-installer\dependencies\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME 
-DDYNAMIC_MZSCH_DLL=\"libracket3m_dcgt6o.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_dcgt6o.dll\" 
-DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"pe
rl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-ucrt-ruby320.dll\" 
-DRUBY_VERSION=32 -DFEAT_HUGE /Fd.\ObjGXOULYHRZAMD64/ /Zi
Linking: link /nologo /opt:ref /LTCG /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib 
gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:AMD64 version.lib  winspool.lib 
comctl32.lib libcmt.lib oleaut32.lib  /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib 
/nodefaultlib:python3.lib    winmm.lib Ws2_32.lib xpm\x64\lib-vc14\libXpm.lib  /PDB:gvim.pdb -debug

`

**Comment by arozehnal** [comment]
I also thought to run scriptnames - there are three cases of loading 
1) ~\vimfiles... # OK
2) d:\u\vim9\vim91 ...    # OK
3) and then two cases where the line starts with 'A:'... - that's suspicious to me
![image](https://github.com/user-attachments/assets/67928e2b-1a6e-45ee-88b4-80d8d0a53dc1)

**Comment by arozehnal** [comment]
and one more thing...
when installing vimsuggest in Windows, vim.plug complained about some inconsistency in "git branch naming"
I saw this for the first time in my life :-(

after some searching I came to:
Plug 'girishji/vimcomplete' , { 'branch': 'main' }
Plug 'girishji/vimsuggest' , { 'branch': 'main' }

then the PlugInstall went correctly
and PlugStatus did not report a problem

**Comment by girishji** [comment]
Maybe using file-separator `/` instead of `\` is causing the problem?

**Comment by girishji** [comment]
I was able to reproduce the problem. The windows version I downloaded from vim.org has v:versionlong 9010000 (same as yours). This does not have patches to fix circular import (without autoload) and does not support classes. Above problem can be resolved easily but you'll run into other issues. I'm going to make a requirement for patched version. Not much can be done here.

**Comment by arozehnal** [comment]
t seems to me that you are too quick to utilize the new vim options :-)
but your plugins seem great!!

**Comment by girishji** [comment]
One of the PRs that fixed circular import was really critical though. They need to update Windows version asap.
