### ISSUE TITLE
complete file paths with env var's

### ISSUE THREAD

**Issue by Konfekt** [girishji/vimsuggest#11]
For example, `:edit $VIMRUNTIME` does not complete

**Comment by girishji** [comment]
Should be fixed now.

**Comment by Konfekt** [comment]
Somehow it still appends the whole expanded path after `$VIMRUNTIME`

![image](https://github.com/user-attachments/assets/f7aa8745-d095-48f2-988c-778522eb6f34)

Tested with 

```vim
set nocompatible
let $LANGUAGE='en_US.utf-8'


let &rtp = '~/.vim/plugged/vimsuggest/' . ',' . &rtp

filetype plugin indent on
syntax on
```

and Vim 9.1.840

**Comment by Konfekt** [comment]
Though the screenshot only shows `$VIM`, it is the same after `$VIMRUNTIME`

**Comment by girishji** [comment]
I tested this scenario and it is working for me. Can you make sure you get `0` when you type `:echo 'edit $VIM' !~ '\$'`?

**Comment by Konfekt** [comment]
Yes, I get 0. However, it's patch level 892, not 840

**Comment by Konfekt** [comment]
I type `:e $VIMRUNTIME/<tab>` and out comes `/usr/...` replacing `<tab>`

**Comment by girishji** [comment]
I am at patch 850.  Do you have this line (file `autoload/vimsuggest/cmd.vim`) ?

<img width="886" alt="Screenshot 2024-11-29 at 4 00 42 PM" src="https://github.com/user-attachments/assets/4a6c76fb-e836-4744-bca5-5d90cc45de26">

**Comment by Konfekt** [comment]
[Yankcode](https://github.com/AaronLasseigne/yank-code/pull/6) gives me

```vim
#  autoload/vimsuggest/cmd.vim (line 201)
if options.wildignore && cmdstr =~# $'^\s*{cmdpat}\s' && cmdstr !~ '\$'
```

**Comment by girishji** [comment]
This sounds impossible. Can you do `echo getcompletion('e $VIM', 'cmdline')` and see what it prints?

**Comment by Konfekt** [comment]
> ~                                                                                  
['VIM', 'VIMRUNTIME']

**Comment by Konfekt** [comment]
The screenshot was by mistake. The same behavior after completing `$VIMRUNTIME`

**Comment by girishji** [comment]
All of this defies logic. Can you put a `echom 'here'` after the `if` statement in line 201 above, and see if it gets printed (`:messages`) when you run your use case? Or, maybe you can attach the whole `cmd.vim` file and I can look into it.

**Comment by Konfekt** [comment]
[cmd.zip](https://github.com/user-attachments/files/17963076/cmd.zip)

Of course. I just reproduced on Debian 12 (after Ubuntu 22.04)

**Comment by Konfekt** [comment]
The `here` is not shown.

**Comment by girishji** [comment]
Sorry for late response. Pl. try now.

**Comment by Konfekt** [comment]
Thank you!
