### ISSUE TITLE
Conflict with backspace in :%s mode 

### ISSUE THREAD

**Issue by M-seas** [girishji/vimsuggest#13]
Vim 9.1 version
VIM-Vi IMproved 9.1 (2024 Jan 02, compiled on Nov 19 2024 23:08:19)
Ms-windows 64-bit graphics/console version with OLE support

Test in Chinese in :%s mode foud plug conflict with ```backspace``` and when search on word it will double type the match word
Simpily in search mode it not raise this conflict.
i have upload a gif to show this error.
![PixPin_2024-11-28_20-10-36](https://github.com/user-attachments/assets/8bcaa79e-e3fb-431e-a582-e41b5deb9521)

**Comment by girishji** [comment]
Thanks for reporting this. Should be fixed now.

**Comment by M-seas** [comment]
> Thanks for reporting this. Should be fixed now.

Worked! Thanks
