### ISSUE TITLE
E1053: Failed to import './exec.vim'  and E117: Unknown function: vimsuggest#addons#addons#Disable in Linux

### ISSUE THREAD

**Issue by M-seas** [girishji/vimsuggest#14]
Vim Version
VIM - Vi IMproven 9.1 (January 2, 2024, compiled on Feb 20, 2024 02:37:30)
Patches Included: 1-115
Jumbo version with GTK2 graphical interface.
 OS Version
Linux version 3.10.0-1160.31.1.el7.x86_64

Handling the VimEnter auto command "*"... function <SNR>51_Reset[3].. vimsuggest#cmd#Teardown[3]..script
A error occurs when /.vim/plugged/vimsuggest/autoload/vimsuggest/addons/addons.vim:
22 lines
E1053: Failed to import './exec.vim'

Handling the VimEnter white command "*": function <SNR>51_Reset[3].. Error occurred at vimsuggest#cmd#Teardown:
3 lines
E117: Unknown function: vimsuggest#addons#addons#Disable

**Comment by girishji** [comment]
This is likely Vim import issue. Can you upgrade your Vim and try again? I had an 'autoload' after 'import' before, but it was triggering another Vim bug. I had to remove deferred import. If you still have issues after upgrading vim I'll look into it.

**Comment by M-seas** [comment]
> This is likely Vim import issue. Can you upgrade your Vim and try again? I had an 'autoload' after 'import' before, but it was triggering another Vim bug. I had to remove deferred import. If you still have issues after upgrading vim I'll look into it.

I have upgrade vim to 9.1-py3 and upgrade the vimsuggest plug
VIM-Vi IMproved 9.1( 2024 Jan 02，compiled on Sep 242024 12:37:04)
This version not trigger the error
