### ISSUE TITLE
ctrl+I key like ^I not worked in :%s mode

### ISSUE THREAD

**Issue by M-seas** [girishji/vimsuggest#15]
Vim 9.1 version
VIM-Vi IMproved 9.1 (2024 Jan 02, compiled on Nov 19 2024 23:08:19)
Ms-windows 64-bit graphics/console version with OLE support

In search mode ```ctrl```+ ```I``` work well
In ```%s``` mode, it not work
I  have upload a gif to show this issue
![PixPin_2024-12-03_11-48-38](https://github.com/user-attachments/assets/b9a401d0-13f3-43d2-8943-689f01424381)

**Comment by Konfekt** [comment]
Could you check whether `has('patch-9.1.0027')`? Which patch level does `:version` show?

This is maybe a side remark: @girishji this is needed for `defer` and the official Windows build, say on Scoop, is a bit out of date and didn't contain any patches after 9.1.

**Comment by M-seas** [comment]
> Could you check whether `has('patch-9.1.0027')`? Which patch level does `:version` show?
> 
> This is maybe a side remark: @girishji this is needed for `defer` and the official Windows build, say on Scoop, is a bit out of date and didn't contain any patches after 9.1.

Yeah, it ```has('patch-9.1.0027')``` 
Also ```:version``` shows ```Included patches: 1-880```
![PixPin_2024-12-03_18-21-37](https://github.com/user-attachments/assets/b47c9b8d-77c3-4fc2-aebe-7278c48a42a4)

**Comment by Konfekt** [comment]
I'm not sure what you expect. `%s/` doesn't complete, but `%s/a` does.
Also `/` does not completes to anything, but only `/a` or `/b`.

**Comment by girishji** [comment]
This is a real bug. Please wait.

**Comment by M-seas** [comment]
> I'm not sure what you expect. `%s/` doesn't complete, but `%s/a` does. Also `/` does not completes to anything, but only `/a` or `/b`.

We may not on the same page, what i expect is to type ```ctrl``` + ```I``` in ```:%s``` and ```:/```mode
when enable the plug, it failed in ```:%s``` mode , by default, it will shows ```^I```
i have upload a gif to show it
![PixPin_2024-12-03_18-21-37](https://github.com/user-attachments/assets/694b9082-d4cf-47e8-9491-eee653684497)

**Comment by girishji** [comment]
Pl. try now. See README. You can set option to use `<C-n>` as trigger. If you want to use Tab for trigger then you may need to use `<C-v><C-I>` to search for tab characters (only when popup menu is open). Option is called `trigger`.

**Comment by M-seas** [comment]
> Pl. try now. See README. You can set option to use `<C-n>` as trigger. If you want to use Tab for trigger then you may need to use `<C-v><C-I>` to search for tab characters (only when popup menu is open). Option is called `trigger`.

Worked!Really thanks
