### ISSUE TITLE
Command Completion fails to change prefix

### ISSUE THREAD

**Issue by toooonyy** [girishji/vimsuggest#16]
First thx for making lots of awesome plugins, I really like them!

But I notice this bug while using the autocompletion for command. In cmdline, when I typed plup vimsuggest starting to suggest like this 

![1](https://github.com/user-attachments/assets/01221f16-2168-4ae9-a105-ec3bb05792da)

Now PlugUpdate is what I'm interested in, so hit tab and the autocompletion gives me this.

![2](https://github.com/user-attachments/assets/42e41877-67a2-4c0d-8ff2-b4ac0ca882f0)

which is not a command.

Call `:VimSuggestDisableUsing` and use vim buildin wildmenu, type `plup` and hit tab
 
![3](https://github.com/user-attachments/assets/ccd418ed-c7e2-47d7-b06d-39ab79d4600e)
now tab again I get the corrected one
![4](https://github.com/user-attachments/assets/1deb14d2-3322-41dc-973f-6de229d6b36a)

Relevant setting: 
```
vimrc
set wildmode=list:longest,list:full
set wildoptions=fuzzy
```
vimsuggest's option is in the screenshot.

**Comment by girishji** [comment]
Thanks. Should be fixed now.

**Comment by toooonyy** [comment]
Thanks! It's all good now.
