### ISSUE TITLE
tab completion before prefix length

### ISSUE THREAD

**Issue by Konfekt** [girishji/vimsuggest#18]
Currently hitting `<tab>`to trigger completion before prefix length shows `<09>`;
Instead, how about falling back to `<tab>` ?

I could not yet wrap my head around how to actually does what `<tab>` is supposed to do (which is `nr2char(&wildcharm)` in scripts).

**Comment by Konfekt** [comment]
See also https://github.com/girishji/vimsuggest/pull/10 implementing `prefix`

**Comment by girishji** [comment]
Is `<09>` the code for `<tab>`? It tries to insert literal tab before _prefix_ length.

**Comment by Konfekt** [comment]
Yes, so I think something like sending `<tab>` instead of `nr2char(&wildcharm)` is going on inside the plugin

**Comment by Konfekt** [comment]
But I couldn't pinpoint where

**Comment by girishji** [comment]
It is done here:

<img width="497" alt="Screenshot 2024-12-10 at 4 47 11 PM" src="https://github.com/user-attachments/assets/972d3cf0-f8a9-4982-9882-38d7bcb54d3f">

Since there is an autocmd to intercept the keystrokes, `<tab>` is handled not as a `wildchar`.

**Comment by girishji** [comment]
Do you want completion window to popup when you hit `<tab>` AND when typed text is less than `prefix`  length?

**Comment by Konfekt** [comment]
Anything's better than outputting `<09>`, yes, the completion window is natural as hitting `<tab>` for me is manual completion (in contrast to autocompletion). The other alternative would be to make `<tab>` do what it would do without this plug-in, but I suppose that's more difficult (and somehow it must be unmapped to make it work?)

**Comment by girishji** [comment]
https://github.com/girishji/vimsuggest/commit/65ea3d5b611be3987d08c7fd1b4226948bd13096

**Comment by girishji** [comment]
Sorry for late response. Should be fixed now.

**Comment by Konfekt** [comment]
Thank you very much, I didn't dare to tackle this and there's no hurry. I took note of the sensibly changed option name, but behavior kept being the same, still emitting `<09>` instead of vimsuggest's completion menu kicking in

**Comment by girishji** [comment]
You have this: https://github.com/girishji/vimsuggest/commit/2dfdd698b9871a33e7755b7e5bd3afcde4a6f7c6 ?
What options are you using?

**Comment by Konfekt** [comment]
> You have this: [2dfdd69](https://github.com/girishji/vimsuggest/commit/2dfdd698b9871a33e7755b7e5bd3afcde4a6f7c6) ?

Yes, it's included.
In fact, `:e<tab>` now works, but after more than one character (but less than `prefixlen`) `:ed` it stops working.
That should be a simple oversight.

What does not work is custom commands, such as, say `:P` which should complete to `:PlugUpdate`.

> What options are you using?

Running `vim --clean -u ~/.viminrc` with the latter reading

```vim
vim9script
set nocompatible
# To avoid scrambled non english letters.
language messages en_US.utf-8

# # Load plugin
# let &rtp = '/usr/share/vim/vim91/plugin' . ',' . &rtp
&rtp = '~/.vim/plugged/vimsuggest/' .. ',' .. &rtp

filetype plugin indent on
syntax on

# # options go here
# set hidden

var vim_suggest = {}
vim_suggest.cmd = {
    enable: true,
    pum: true,
    exclude: [],
    onspace: ['b\%[uffer]', 'colo\%[rscheme]'],
    alwayson: true,
    popupattrs: {},
    wildignore: true,
    addons: true,
    ctrl_np: false,
    reverse: false,
    prefixlen: 3,
}
vim_suggest.search = {
    enable: true,
    pum: true,
    fuzzy: false,
    alwayson: true,
    popupattrs: {
      'maxheight': 12
    },
    range: 100,
    timeout: 200,
    async: true,
    async_timeout: 3000,
    async_minlines: 1000,
    highlight: true,
    ctrl_np: false,
    prefixlen: 3,
}
autocmd VimEnter * call g:VimSuggestSetOptions(vim_suggest)

# ex:ft=vim
```

Then `:ed<tab>` shows `^I`, whereas with my `vimrc` it shows `<09>`.

**Comment by girishji** [comment]
Should be fixed. Please try now.

**Comment by Konfekt** [comment]
Thank you!
