### ISSUE TITLE
Reverse UP and DOWN

### ISSUE THREAD

**Issue by poslat-pismo** [girishji/vimsuggest#19]
Hello! I'm using `'reverse': v:true` and `'trigger': 'tn'`
Is there a way to reverse **UP** and **DOWN** keys inside **pum**?

**Comment by girishji** [comment]
Reverse **UP/DOWN** arrow keys, but not `<C-n><C-p>`? If so, it cannot be done in Vim. Vim sends the same keycode for `<C-n>` and **DOWN**. They are bound together. If you change **UP/DOWN** then `<C_N/P>` will also get reversed and it will not be intuitive. This is a Vim limitation.

**Comment by girishji** [comment]
Try now please.

**Comment by poslat-pismo** [comment]
Thank you very much! Now works as expected.
