### ISSUE TITLE
Errors when using packadd

### ISSUE THREAD

**Issue by briancarbone** [girishji/vimsuggest#2]
I typed `:` to move to the command line and it just prints an error immediately.

```
Error detected while compiling CmdlineEnter Autocommands for ":"..function <SNR>26_State.new[6]..<SNR>26_FilterFn:
line   24:
E354: Invalid register name: '+'
```

A second time prints:

```
Error detected while processing CmdlineEnter Autocommands for ":":
E1091: Function is not compiled: new
```

**Comment by briancarbone** [comment]
Mistake in config.

**Comment by briancarbone** [comment]
Nevermind, still happening... not sure why.

**Comment by girishji** [comment]
Can you do `:vim9 @+ = 'foo bar'` and see if there is error?

`E354: Invalid register name: '+'` is strange. Do you have latest Vim?

**Comment by girishji** [comment]
Upgrade to new version pl

**Comment by briancarbone** [comment]
Seems to be working now.
