### ISSUE TITLE
popup suggesting completion of all possible command arguments despite filter in custom completion returning none

### ISSUE THREAD

**Issue by Konfekt** [girishji/vimsuggest#20]
In https://gist.github.com/Konfekt/5748fbe2d72749ab9b2ea8362f703a7e#file-aichat-vim-L57 all arguments that can be supplied to a command, say `:ACAppend` begin with `/`.
Now the check

```vim
    call map(roles, '"/" . v:val')
    return filter(roles, 'v:val =~ "^' . a:A . '"')
```

rather appends `/` to each argument of the list instead of checking if the argument a:A begins with `/` when comparing them.

This likely causes vimsuggest, say after `:ACAppend a `, to suggest all elements in the array of arguments instead of doing so only after `/`.

I wonder if there's an easy fix on vimsuggest's side, or rather the `/` in the comparison has to swap places.
Of course, this is the more natural thing to do in first place, but for some reason didn't work as desired as I faintly remember.

**Comment by girishji** [comment]
Can you do `:echo getcompletion('ACAppend a', 'cmdline')` and see what it prints? It should only complete after `/` is typed.

**Comment by Konfekt** [comment]
The output of `:echo getcompletion('ACAppend a', 'cmdline')` is `[]` but `:echo getcompletion('ACAppend a ', 'cmdline')` (with the trailing space after `a`) gives the whole array `[...]` of possible `/role` completions

**Comment by girishji** [comment]
You can tweak `s:AIChatRoleCompletion(A,L,P)` such that you test how many space-separated words are there before cursor and adjust the completion list. If there is no `/` then do not return the list, but return `[]`, and so on. This plugin relies on `getcompletion()`. You need to adjust the return value there.

**Comment by Konfekt** [comment]
Adding

```vim
    if a:L =~# '\s$'
      return ''
    endif
```

seems to work, though I thought it would break completion if the line would end with a space and one's completing in the middle of it, but fine so far
