### ISSUE TITLE
VSFile for git

### ISSUE THREAD

**Issue by JetSetIlly** [girishji/vimsuggest#3]
In `scope` there is `fuzzy.GitFile()` in addition to `fuzzy.File()`. It would be nice to have an equivalent in `vimsuggest`. `VSGitFind` or something like that.

At the moment, I'm doing this:

```
function! DoFZFind()
	if !empty(glob(".git"))
		let g:vimsuggest_fzfindprg = 'git ls-tree --full-tree -r --name-only HEAD'
		call feedkeys(":VSFind ")
	else
		let g:vimsuggest_fzfindprg = 'find $* \! \( -path "*/.*" -prune \) -type f -follow'" 
		call feedkeys(":VSFind ")
	endif
endfunction
nnoremap <C-p> <ESC>:call DoFZFind()<CR>
```

Which is fine, but it seems a bit complicated to have in .vimrc file.

In fact something like a `VSSmartFind` would also be a nice addition. I'm imagining that this would behave similar to my DoFZFind() function I quoted above. ie. Fuzzy search for git files if the current directory contains a .git file and a normal file search otherwise.

Thanks for these plugins (vimcomplete, vimsuggest, etc.). They're great!

Steve

**Comment by gcanat** [comment]
I think you have a small typo in your snippet :
```diff
- if !empty(glob(".git"))
+ if !empty(glob(".git/*"))
```
or maybe `isdirectory(".git")` is enough 99% of the time

**Comment by JetSetIlly** [comment]
> I think you have a small typo in your snippet :
> 
> ```diff
> - if !empty(glob(".git"))
> + if !empty(glob(".git/*"))
> ```
> 
> or maybe `isdirectory(".git")` is enough 99% of the time

Maybe `isdirectory()` is a better way of doing it. It makes the intention of the code more clear

**Comment by girishji** [comment]
Sorry for late reply. I added :VSGitFind. Would something like this work?

**Comment by JetSetIlly** [comment]
> Sorry for late reply. I added :VSGitFind. Would something like this work?

Yes. That's perfect. Thank you
