### ISSUE TITLE
`fd` example  for `VSFindL` should use the `--glob` option

### ISSUE THREAD

**Issue by gcanat** [girishji/vimsuggest#4]
Hey, great plugin once again!

It seems to me that the example given for using `VSFindL` with `fd` is not working.
It works with:
```vimscript
let g:vimsuggest_findprg = 'fd --type f --glob'
```
Side note: for me, on Ubuntu, it is `fdfind` not `fd` but I doubt this matters.

And btw, I havent been able to make VSGrep work with `rg` so far using the given example (and a few other things I tried).
Edit: got `rg` to work by adding `.` at the end:
```vimscript
nnoremap <key> :VSGrep "" .<left><left><left>
```

**Comment by girishji** [comment]
Thanks for the feedback! I've updated the docs.

For rg:
```
   let g:vimsuggest_grepprg = 'rg --vimgrep --smart-case $* .'
```

I think `fd` does not need quotes. So:
```
   nnoremap <key> :VSFindL<space>
```

--glob is a choice. By default `fd` uses regex search.
