### ISSUE TITLE
Option 'alwayson' appears to deactivate popup

### ISSUE THREAD

**Issue by engeljh** [girishji/vimsuggest#5]
When I try to have suggestions triggered by Tab, by adding the following to my .vimrc (which is in vim9script):

var vim_suggest = {}
vim_suggest.cmd = { 'alwayson': false }
autocmd VimEnter * g:VimSuggestSetOptions(vim_suggest)

the suggestions are shown when I hit Tab, but not in a popup window.  Can you help?

**Comment by girishji** [comment]
Please try now.

**Comment by engeljh** [comment]
Working now, thanks.
