### ISSUE TITLE
Idea: Option for reverse sorted results

### ISSUE THREAD

**Issue by JetSetIlly** [girishji/vimsuggest#6]
Because the size of the popup window changes I sometimes find it awkward to read the results of the fuzzy search. It would be better I think, if the results in the popup were reversed. In other words, the best fuzzy match will appear at the bottom of the popup nearest to the typing area in a consistent location.

A universal option for all results to be reverse sorted would be very helpful.

I also think that for very long results the popup would need to be pre-scrolled to the bottom.

**Comment by gcanat** [comment]
Personnally I set the option `popupattrs` with `{'maxheight': 20}`, because it keeps the popup window to a reasonable size and if there's more than 20 results, it probably means I need to narrow down my search more.
For me 20 works well, for some it might be 30 or 10... adjust to your liking.

**Comment by girishji** [comment]
Added this option. Pl. try.

**Comment by girishji** [comment]
Added this option. Pl. try.

**Comment by JetSetIlly** [comment]
> Added this option. Pl. try.

That works very well. Thank you

**Comment by JetSetIlly** [comment]
This seems to be a bug:

![image](https://github.com/user-attachments/assets/834c2f69-8680-45aa-9e38-a2dfdd48c68f)

In this example, I've typed "gl32" and selected the third entry from the bottom. However, the string "gl32" has been highlighted in the third entry from the top

**Comment by girishji** [comment]
Can you upgrade and try now. You should see 'gl32' from all lines highlighted with PmenuMatch and selected line with PmenuMatchSel highlight groups. (check if those groups are set in your colorscheme)

**Comment by JetSetIlly** [comment]
> Can you upgrade and try now. You should see 'gl32' from all lines highlighted with PmenuMatch and selected line with PmenuMatchSel highlight groups. (check if those groups are set in your colorscheme)

No. This doesn't work unfortunately.

PmenuMatch and PmenuMatchSel are both linked to other highlight groups.

```
PmenuMatch     xxx links to Pmenu
PmenuMatchSel  xxx links to PmenuSel
Pmenu          xxx ctermfg=103 ctermbg=235 guifg=#908caa guibg=#2a273f
PmenuSel       xxx ctermfg=189 ctermbg=237 guifg=#e0def4 guibg=#393552
```

For clarification, this is a video of the problem. I'm selecting with Tab and Shift-Tab

https://github.com/user-attachments/assets/0eeb4d66-89fd-41a7-b386-134c81e5eb1a

**Comment by girishji** [comment]
Sorry I misunderstood the problem. Pl. try now.

**Comment by JetSetIlly** [comment]
> Sorry I misunderstood the problem. Pl. try now.

Yes. That's perfect. Thank you
