### ISSUE TITLE
Repeated pressing of tab  required when fuzzy searching with 'alwayson' set to false

### ISSUE THREAD

**Issue by engeljh** [girishji/vimsuggest#7]
I set 'alwayson' to false.  When I type :VSFind and some characters, and then hit tab, the popup opens, but then when I type more characters to narrow the search down, the popup closes until I hit tab again, so that I can't see the options narrow as I type.  Is there a way to avoid this, so that I have to hit tab only once?

**Comment by girishji** [comment]
Pl. try now. If there are still issues, please report back.

**Comment by engeljh** [comment]
Hi,

Now, tab doesn't work at all.  I get

Error detected while processing function <SNR>105_DoComplete:
line   31:
E1174: String required for argument 3

whenever I press tab.

Thanks.
________________________________

**Comment by girishji** [comment]
Can you post your configuration?

**Comment by engeljh** [comment]
var vim_suggest = {}
  vim_suggest.cmd = { 'fuzzy': true, 'onspace': 'buffer', 'alwayson': false }
  g:vimsuggest_fzfindprg = 'fd --type f'
  autocmd VimEnter * g:VimSuggestSetOptions(vim_suggest)
  nnoremap <leader>bu :buffer<space>
  nnoremap <leader>vf :VSFind<space>

But things are behaving in the same way even with 'alwayson' set to true.  Then, as soon as I enter a command I get the error.
________________________________

**Comment by girishji** [comment]
I cannot reproduce this. What version of Vim are you using (`:version`)? which OS?

**Comment by engeljh** [comment]
MacVim (9.1) on MacOS 15.

The plugin works if I don't do

 autocmd VimEnter * g:VimSuggestSetOptions(vim_suggest).

though the, obviously, 'alwayson' is true.  And when I try to call the function without the autocommand, I get E117, unknown function, even though I installed it the plugin by hand in the start directory with all my other plugins.
________________________________

**Comment by girishji** [comment]
Ok, I reproduced the problem. Very busy today, but will get to it asap.

**Comment by girishji** [comment]
You've made a mistake in your config. It should be `'onspace': ['buffer']`. See README.

**Comment by engeljh** [comment]
Oh, I'm sorry.  And thanks for fixing the other problem with tab.
________________________________
