### ISSUE TITLE
minimal prefix length

### ISSUE THREAD

**Issue by Konfekt** [girishji/vimsuggest#9]
Similar to https://github.com/lifepillar/vim-mucomplete/blob/03bcd4a7dfe0a2f6d432e8ce936d35273a15209d/doc/mucomplete.txt#L646 how about optionally configuring the minimal prefix length when autocompletion is to kick in? When doing `:q` or `:wa`, autocompletion is rather distracting than needed.

**Comment by Konfekt** [comment]
Great plugin, by the way, thank you very much

**Comment by bscuron** [comment]
Created #10
